name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo mkdir -p /workdir
        sudo chown $USER:$GROUPS /workdir

    - name: Install Flutter 3.0.5
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.0.5'
        channel: 'stable'

    - name: Build with Flutter
      run: |
        flutter build web

    - name: Organize files
      run: |
        tar -zcvf /workdir/driveindex-web.tar.gz ./build/web/* --transform s=build/web/==

    - name: Upload to release
      if: startsWith(github.ref, 'refs/tags/')
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{ github.ref }}
        file: "/workdir/*"
        overwrite: true
        file_glob: true
